#ifndef ARCH_ARM_MACH_MSTAR_INCLUDE_MSTARV7_H_
#define ARCH_ARM_MACH_MSTAR_INCLUDE_MSTARV7_H_

#define MSTAR_SRAM			0xa0000000
#define MSTAR_DRAM			0x20000000

#endif /* ARCH_ARM_MACH_MSTAR_INCLUDE_MSTARV7_H_ */
